-- AlterEnum
ALTER TYPE "ServiceRequestType" ADD VALUE IF NOT EXISTS 'WATER';
ALTER TYPE "ServiceRequestType" ADD VALUE IF NOT EXISTS 'UTENSILS';
ALTER TYPE "ServiceRequestType" ADD VALUE IF NOT EXISTS 'CLEANING';
